    - name: Set Hostname
      become: true
      ansible.builtin.hostname:
        name: "{{ server_hostname }}"

    - name: Replace old hostname with new hostname
      become: true
      ansible.builtin.replace:
        path: /etc/hosts
        regexp: '(127[.]0[.]1[.]1)(\s+)(.*)(\s+.*)?$'
        replace: '\g<1>\g<2>{{ server_hostname }}\n'
