- hosts: all
  name: Get pi stats
  tasks:
    - name: Run vc gencmd get_throttled
      ansible.builtin.command: vcgencmd version; vcgencmd get_throttled; vcgencmd measure_volts; vcgencmd measure_temp;vcgencmd measure_clock arm;
      register: out
      ansible.builtin.debug: var=out.stdout_lines
      changed_when: false