- hosts: all
  name: Install PiScrape
  vars:
    server_hostname: "piscrape" # Variable for renaming server, github key.
    server_service_username: "james" # Service account name

  roles:
    - system-configuration/github-deploy-key
    - system-configuration/use-github-key-for-ssh
    - application/docker
    - system-configuration/unattended-upgrades
    - system-configuration/network/dhcp
    - system-configuration/hostname-rename
    - system-configuration/update/raspi4
    - application/cargiantscrape
    - system-configuration/network/wifi
