# code: language=ansible
- hosts: all 
  name: Install Pi Hole 2
  vars:
    server_hostname: "pihole2" # Variable for renaming server, github key.
    server_service_username: "james" # Service account name
    docker_compose_files:
      - cloudflared-pihole-docker-compose.yml
    enabled_vlans:
      - 70
  roles:
    - system-configuration/github-deploy-key
    - system-configuration/use-github-key-for-ssh
    - roles/application/docker
    - application/docker-compose-apps
    - system-configuration/unattended-upgrades
    - system-configuration/hostname-rename
    - system-configuration/update/raspi4
    - system-configuration/network/wifi
