all:
  vars:
    ansible_user: james
    # Backup IP in case mdns fails resolution
    host_ip_lookup:
      hassio.local: 192.168.1.100
      unifipi.local: 192.168.1.70
      homebridge.local: 192.168.1.144
      pihole2.local: 10.10.70.61
      garageprinterserver.local: 10.10.70.200
      piscrape.local: 10.10.70.187
  children:
    linuxservers:
      hosts:
        hassio.local:
        unifipi.local:
        homebridge.local:
        pihole2.local:
        garageprinterserver.local:
        piscrape.local:
    pikvms:
      hosts:
        pikvm1.local:
        pikvm2.local:
        pikvm3.local:
      vars:
        ansible_user: root
