
- name: Gather facts
  setup:
    gather_subset: hardware

- name: Install OS-agent for aarch64
  ansible.builtin.apt:
    deb: https://github.com/home-assistant/os-agent/releases/download/1.5.1/os-agent_1.5.1_linux_aarch64.deb
    state: present
  become: true
  when: ansible_architecture == 'aarch64'
  # changed_when: os_agent_check_deb.rc == 1

- name: Install OS-agent for amd64
  ansible.builtin.apt:
    deb:  https://github.com/home-assistant/os-agent/releases/download/1.5.1/os-agent_1.5.1_linux_x86_64.deb
    state: present
  become: true
  when: ansible_architecture == 'x86_64'

- name: Check os-agent working properly
  ansible.builtin.command:
    cmd: "gdbus introspect --system --dest io.hass.os --object-path /io/hass/os"
  register: "gdbus"
  changed_when: gdbus.rc != 0
  failed_when: gdbus.rc > 1
  
