# - name: Debug role_path variable
#   debug:
#     var: role_path

# - name: Copy Docker Compose files to server
#   ansible.builtin.copy:
#     src: "{{ role_path }}/files/"
#     dest: "/home/{{ ansible_user }}/docker-src"

# - name: Combine Docker Compose files
#   community.general.docker_compose:
#     project_src: "/home/{{ ansible_user }}/docker-src" # Path to your project directory containing the Docker Compose files
#     files: "{{ docker_compose_files   }}"
#     state: present
#     pull: true
#   when: docker_compose_files | length > 1




- name: Copy Docker Compose files to server
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/home/{{ ansible_user }}/docker-src/"
    mode: '0644'
  loop: "{{  docker_compose_files }}"

  #for pi hole generate a password and put it in
- name: Generate random password
  set_fact:
    random_password: "{{ lookup('password', '/dev/null length=20 chars=ascii_letters,digits,special') }}"

- name: Create password file
  copy:
    content: "{{ random_password }}"
    dest: "/home/{{ ansible_user }}/docker-src/"
  when: "'cloudflared-pihole-docker-compose.yml' in docker_compose_files"



- name: Create and start services
  community.docker.docker_compose:
    project_src: /home/{{ ansible_user }}/docker-src/
    files:
      "{{  docker_compose_files }}"
    pull: true
    state: present
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output
