# - name: Debug role_path variable
#   debug:
#     var: role_path

# - name: Copy Docker Compose files to server
#   ansible.builtin.copy:
#     src: "{{ role_path }}/files/"
#     dest: "/home/{{ ansible_user }}/docker-src"

# - name: Combine Docker Compose files
#   community.general.docker_compose:
#     project_src: "/home/{{ ansible_user }}/docker-src" # Path to your project directory containing the Docker Compose files
#     files: "{{ docker_compose_files   }}"
#     state: present
#     pull: true
#   when: docker_compose_files | length > 1
- name: Copy Docker Compose files to server
  ansible.builtin.copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/home/{{ ansible_user }}/docker-src/"
    mode: '0644'
  loop: "{{  docker_compose_files }}"

- name: Create and start services
  community.docker.docker_compose:
    project_src: /home/{{ ansible_user }}/docker-src/
    files:
      "{{  docker_compose_files }}"
    pull: true
    state: present
  register: output

- name: Show results
  ansible.builtin.debug:
    var: output
