# code: language=ansible
- hosts: all
  name: Install Garageprinterserver
  vars:
    server_hostname: "garageprinterserver" # Variable for renaming server, github key.
    server_service_username: "james" # Service account name
    enabled_vlans:
  roles:
    - system-configuration/github-deploy-key
    - system-configuration/use-github-key-for-ssh
    - application/cups-print-server
    - system-configuration/unattended-upgrades
    - system-configuration/hostname-rename
    - system-configuration/update
    - system-configuration/network/wifi
