# code: language=ansible
# template ansible playbook for installing a raspbian 32 bit with docker
#
- hosts: all
  name: Install Home assistant
  vars:
    server_hostname: "pi-node1" # Variable for renaming server, github key. 
    server_service_username: "james" # Service account name
    ansible_user: "root"
    enabled_vlans: # Enabled VLANS
      - VLAN30
      - VLAN70
    compose_files: # For docker-compose-apps
      - doods-docker-compose.yml
  roles: 
    - system-configuration/github-deploy-key
    - system-configuration/use-github-key-for-ssh
    - application/docker32bit
    - system-configuration/unattended-upgrades
    - system-configuration/network/dhcp
    - system-configuration/hostname-rename
    - system-configuration/update/raspi4
    - system-configuration/reboot
