version: '3.8'

networks:
  my_network:
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  ansible-test-instance:
    container_name: ansible-test-instance
    image: ansible-test-instance
    networks:
      my_network:
        ipv4_address: 172.18.0.2
