- hosts: linuxservers
  name: Check and install updates on Ansible nodes
  gather_facts: false
  tasks:
    - name: Run APT update
      become: true
      ansible.builtin.apt:
        update_cache: true
        upgrade: true
        cache_valid_time: 86400

    - name: Run docker compose update
      ansible.builtin.command: find /home -name docker-compose.yml
      register: compose_out
      changed_when: false

    - name: Print docker composes
      ansible.builtin.debug:
        var: compose_out.stdout_lines

- hosts: pikvms
  name: Update PiKVMs
  gather_facts: false
  become: true
  vars:
    ansible_remote_tmp: /tmp/ansible
  pre_tasks:
    - name: Switch to rw mode
      ansible.builtin.command: rw
      changed_when: false
  tasks:
# Must run RW via ssh on the machines first
    - name: Gather facts
      ansible.builtin.gather_facts:
        parallel: true

    - name: Update Repo
      community.general.pacman:
        state: latest
        update_cache: true

    - name: Upgrade all packages
      community.general.pacman:
        state: latest
        upgrade: true
        force: true

    - name: Restart
      become: true
      ansible.builtin.reboot:
        reboot_timeout: 30
        test_command: uptime

  post_tasks:
    - name: Set Read Only FS
      become: true
      ansible.builtin.command:
        cmd: ro
      changed_when: false
