- name: Install network manager
  ansible.builtin.apt:
    name: network-manager
    state: present
    update_cache: true

- name: Enable & Start Network manager service
  ansible.builtin.service:
    name: NetworkManager
    enabled: true
    state: started
  when: not skip_wifi_config_role

- name: Configure network
  community.general.nmcli:
    state: present
    conn_name: eth0
    ifname: eth0
    type: ethernet
    method6: "disabled"
  when: not skip_wifi_config_role

- name: Create VLANs
  community.general.nmcli:
    type: vlan
    conn_name: "eth0.{{ item }}"
    vlandev: eth0
    vlanid: "{{ item }}"
    state: present
    method6: "disabled"
    mac: stable
  when: (not skip_wifi_config_role) or (enabled_vlans | length > 0)
  loop: "{{ enabled_vlans }}"
