    # network configuration
    - name: Install network manager
      become: true
      ansible.builtin.apt:
        name: NetworkManager
        state: present

    - name: Enable & Start Network manager service
      become: true
      ansible.builtin.service:
        name: NetworkManager
        enabled: true
        state: started

# configure network last incase anciblen loses connection
    - name: Configure network
      become: true
      community.general.nmcli:
        state: present
        conn_name: eth0
        ifname: eth0
        type: ethernet
        method6: "disabled"

    - name: Create VLAN 20
      become: true
      community.general.nmcli:
        type: vlan
        conn_name: eth0.20
        vlandev: eth0
        vlanid: 20
        state: present
        method6: "disabled"
        mac: stable
      when: item == "VLAN20"
      with_items: "{{ enabled_vlans }}"

    - name: Create VLAN 30
      become: true
      community.general.nmcli:
        type: vlan
        conn_name: eth0.30
        vlandev: eth0
        vlanid: 30
        state: present
        method6: "disabled"
        mac: stable
      when: item == "VLAN30"
      with_items: "{{ enabled_vlans }}"

    - name: Create VLAN 70
      become: true
      community.general.nmcli:
        type: vlan
        conn_name: eth0.70
        vlandev: eth0
        vlanid: 70
        state: present
        method6: "disabled"
        mac: stable
      when: item == "VLAN70"
      with_items: "{{ enabled_vlans }}"
