version: '3.8'

networks:
  my_network:
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  ansible-test-instance:
    container_name: ansible-test-instance
    image: ansible-test-instance:latest
    init: true
    networks:
      my_network:
        ipv4_address: 172.18.0.2
    ports:
      - "2222:22"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: ["/bin/bash", "-c", "service ssh start && dockerd & wait"]