- name: Check if machine is a container
  debug:
    var: ansible_virtualization_type
  register: is_container.rc

- name: Restart real machine
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible. System will be restarted."
  when: is_container.vars.ansible_virtualization_type != "container"