    - name: Create the wifi connection
      become: true
      community.general.nmcli:
        type: wifi
        conn_name: mainwifi
        ifname: wlan0
        ssid: "{{ wifi_ssid }}"
        wifi_sec:
          key-mgmt: wpa-psk
          psk: "{{ wifi_password }}"
        autoconnect: true
        state: present